#!/usr/bin/env bash
# Configure your domain

extract_record_info () {
    # dig @server(name or IP address) name(name of the resource record) type(type of query is required - ANY, A, MX, SIG)
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# checking if command line arguments are provided
if [ "$#" -eq 2 ]; then
	extract_record_info "$1" "$2"
else
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"; do
		extract_record_info "$1" "$subdomain"
	done
fi
