#!/usr/bin/env bash
# Installing nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart