#!/usr/bin/env bash
# Installing nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo '<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="refresh" content="0; URL=https://www.youtube.com/">
</head>
<body>
    <p>Redirecting to YouTube...</p>
</body>
</html>' | sudo tee /var/www/html/redirect_me.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart