#!/usr/bin/env bash
# Configuring HAProxy load balancer

# update the package list 
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy 2.9
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 20767-web-01 54.242.185.103:80 check
    server 20767-web-02 18.235.248.173:80 check
"
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
