#!/usr/bin/env bash
# Installing nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown "$USER":"$USER" /var/www/html/index.nginx-debian.html
# configure nginx to listen on all IPv4 addresses
sudo sed i 's/listen 80;/listen *:80:/g' /etc/m\nginx/nginx.conf

sudo service nginx restart
