#!/usr/bin/env bash
# This script is displaying "Best School" 9 times then "Hi" then "Best School" one last time
for ((i=0; i<10; i++)); do
    echo "Best School"
        if [ "$i" -eq 8 ]
        then
            echo "Hi"
        fi
done