#!/usr/bin/env bash
# This script is displaying "Best School"  but on the 4th loop it displays "bad luck" and in 8th loop where it displays "good luck"
count=1
while [ $count -lt 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done