#!/usr/bin/env bash
# This script is displaying numbers 1-20 but on the 4th loop it displays "bad luck from China " or in 9th loop where it displays "bad luck from Japan" or in 17th loop where it displays "bad luck from Italy"
count=1
while [ $count -lt 21 ]; do
case $count in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    *)
        echo $count
        ;;
esac
count=$((count + 1))
done