#!/usr/bin/env bash
# This script is displaying numbers 1-20 but on the 4th loop it displays "bad luck from China " or in 9th loop where it displays "bad luck from Japan" or in 17th loop where it displays "bad luck from Italy"
count=1
while [ $count -lt 21 ]; do
echo $count
count=$[$count + 1]
    if [ $count -eq 5 ]; then
        echo "bad luck from China"
    elif [ $count -eq 10 ]; then
        echo "bad luck from Japan"
    elif [ $count -eq 18 ]; then
        echo "bad luck from Italy"
    fi
done