#!/usr/bin/env bash
# This script counts down the minutes for 12 hours
Hour=0
while [ $Hour -lt 13 ]; do
echo "Hour: " $Hour
    minutes=1
    while [ $minutes -lt 60 ]; do
    echo $minutes
    minutes=$((minutes + 1))
    done
Hour=$((Hour + 1))
done