#!/usr/bin/env bash
# This script counts down the minutes for 12 hours
Hour=0
minutes=1
while [ $Hour -lt 13 ]; do
echo "Hour: " $Hour
    while [ $minutes -lt 60 ]; do
    echo $minutes
    minutes=$[$minutes + 1]
    done
    minutes=1
Hour=$[$Hour + 1]
done